### ISSUE TITLE
Docker rootless mode can't work in macos's docker container

### ISSUE THREAD

**Issue by tao12345666333** [rootless-containers/rootlesskit#201] opened 2021-01-05 16:25 UTC
I try to use Docker Desktop for Mac to run `docker:dind-rootless` container but it fails.

```
➜  ~ docker run --rm --privileged -d docker:dind-rootless
Unable to find image 'docker:dind-rootless' locally
dind-rootless: Pulling from library/docker
801bfaa63ef2: Already exists
4f7dc993c79e: Already exists
d39d95e4997f: Already exists
1cda4b703d87: Already exists
54e5375350ea: Already exists
f08cd1b3bb1b: Already exists
8e17d04e0c68: Already exists
76fab333a5ce: Already exists
4dc477ada5f2: Already exists
9f57ce55fb4f: Already exists
a0e22f9cd8f9: Already exists
3e3b3243eb4f: Pull complete
b81d89c02269: Pull complete
2e167115e305: Pull complete
2b9e5cbb9f53: Pull complete
b473ac371011: Pull complete
Digest: sha256:4943cc5bdd2f76f357abbc3bbfffa12502670bdc21f004022e8683368699b536
Status: Downloaded newer image for docker:dind-rootless
8f4bd8e896e344325fca040f02772f10cfb77e56a32d711b64ccab2e654d3836
➜  ~ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                    NAMES
8f4bd8e896e3   docker:dind-rootless   "dockerd-entrypoint.…"   7 seconds ago   Up 6 seconds   2375-2376/tcp            trusting_morse
19f70a932800   debian                 "bash"                   7 hours ago     Up 7 hours                              busy_murdock
919f4f6411a6   registry:2             "/entrypoint.sh /etc…"   2 weeks ago     Up 9 hours     0.0.0.0:5000->5000/tcp   cache
➜  ~ docker exec -it 8f4bd8e896e3 sh
/ $ docker version
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:28:35 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
/ $
/ $ %                                                                                                                                    
➜  ~ docker logs 8f4bd8e896e3
Generating RSA private key, 4096 bit long modulus (2 primes)
............................................................................................................................................................................................................................................++++
....++++
e is 65537 (0x010001)
Generating RSA private key, 4096 bit long modulus (2 primes)
.........................................++++
...........................................................................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = docker:dind server
Getting CA Private Key
/certs/server/cert.pem: OK
Generating RSA private key, 4096 bit long modulus (2 primes)
...................................................................................................................................................................................................++++
.....................++++
e is 65537 (0x010001)
Signature ok
subject=CN = docker:dind client
Getting CA Private Key
/certs/client/cert.pem: OK
open: Permission denied
[rootlesskit:child ] error: executing [[ip tuntap add name tap0 mode tap] [ip link set tap0 address 02:50:00:00:00:01]]: exit status 1
```

When I started a debian container and manually performed related installation operations, and modified `dockerd-rootless.sh` to add the `--debug`  parameter to it, I saw the following errror:

```
rootless@36bf32258181:~$ PATH=/home/rootless/bin:/sbin:/usr/sbin:$PATH dockerd-rootless.sh
+ [ -w ]
+ [ -w /home/rootless ]
+ rootlesskit=
+ which docker-rootlesskit
+ which rootlesskit
+ rootlesskit=rootlesskit
+ break
+ [ -z rootlesskit ]
+ :
+ :
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ [ -z ]
+ which slirp4netns
+ [ -z ]
+ which vpnkit
+ net=vpnkit
+ [ -z ]
+ mtu=1500
+ [ -z ]
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ exec rootlesskit --net=vpnkit --mtu=1500 --debug --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /home/rootless/bin/dockerd-rootless.sh
WARN[0000] The host root filesystem is mounted as "master:131". Setting child propagation to "rslave" is not supported.
DEBU[0000] child: got msg from parent: {Stage:0 Message0:{} Message1:{StateDir: Network:{Dev: IP: Netmask:0 Gateway: DNS: MTU:0 Opaque:map[]} Port:{Opaque:map[]}}}
DEBU[0000] connecting to VPNKit vmnet at /tmp/rootlesskit691763345/vpnkit-ethernet.sock as af2db94c-0ee4-41a3-b587-519de9857fc9
DEBU[0000] connected to VPNKit vmnet
DEBU[0000] child: got msg from parent: {Stage:1 Message0:{} Message1:{StateDir:/tmp/rootlesskit691763345 Network:{Dev:tap0 IP:192.168.65.3 Netmask:24 Gateway:192.168.65.1 DNS:192.168.65.1 MTU:1500 Opaque:map[vpnkit.mac:02:50:00:00:00:01 vpnkit.socket:/tmp/rootlesskit691763345/vpnkit-ethernet.sock vpnkit.uuid:af2db94c-0ee4-41a3-b587-519de9857fc9]} Port:{Opaque:map[builtin.readypipepath:/tmp/rootlesskit691763345/.bp-ready.pipe builtin.socketpath:/tmp/rootlesskit691763345/.bp.sock]}}}
DEBU[0000] executing [ip link set lo up]
DEBU[0000] executing [ip tuntap add name tap0 mode tap]
open: Permission denied
[rootlesskit:child ] error: exit status 1
executing [[ip tuntap add name tap0 mode tap] [ip link set tap0 address 02:50:00:00:00:01]]
github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.startVPNKitRoutines
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:169
github.com/rootless-containers/rootlesskit/pkg/network/vpnkit.(*childDriver).ConfigureNetworkChild
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/pkg/network/vpnkit/vpnkit.go:159
github.com/rootless-containers/rootlesskit/pkg/child.setupNet
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/pkg/child/child.go:144
github.com/rootless-containers/rootlesskit/pkg/child.Child
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/pkg/child/child.go:237
main.main.func2
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:182
github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli/v2.(*App).RunContext
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli/v2/app.go:322
github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli/v2.(*App).Run
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/vendor/github.com/urfave/cli/v2/app.go:224
main.main
	/tmp/tmp.vwaEfFtxnf/src/github.com/rootless-containers/rootlesskit/cmd/rootlesskit/main.go:191
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by AkihiroSuda** [comment] 2021-01-05 18:05
Duplicate of https://github.com/docker/for-mac/issues/3838

Workaround https://github.com/docker/for-mac/issues/3838#issuecomment-527095919

**Closed by AkihiroSuda** 2021-01-05 18:05 UTC
