### ISSUE TITLE
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown <file>: invalid argument

### ISSUE THREAD

**Issue by dg424** [rootless-containers/rootlesskit#304] opened 2022-05-09 14:48 UTC
Hi,

I'm getting the following error when running an image under rootless which runs fine under the regular Docker client - "failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown <file>: invalid argument".

Regular Docker, works fine and shows a non-root user as owning the file:

$ docker run --rm -it --entrypoint sh gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu:v0.7.0 -c "ls -l /usr/local/bin/docker-credential-gcr"
-rwxr-x--x 1 **jovyan users** 9390082 Feb 10  2018 /usr/local/bin/docker-credential-gcr

Rootless:

$ docker run --rm -it --entrypoint sh gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu:v0.7.0 -c "ls -l /usr/local/bin/docker-credential-gcr"
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /usr/local/bin/docker-credential-gcr: invalid argument

$ docker --version
Docker version 20.10.15, build fd82621

Any ideas why it works fine outside of rootless, but fails with rootless ?

**Comment by AkihiroSuda** [comment] 2022-05-23 01:59
Closing as a duplicate of https://github.com/moby/moby/issues/43576

**Closed by AkihiroSuda** 2022-05-23 01:59 UTC
Labels: duplicate
